beta: 4.0
conv: true
decoder_hidden_sizes:
- 16
- 113
- 139
- 169
dropout: 0.2
encoder_hidden_sizes:
- 16
- 185
- 32
- 243
freeze_encoder: false
hidden_size: 2
input_size:
- 4
- 64
- 64
latent_dim: 2
learning_rate: 0.001
noise: 0.01
num_classes: 11
output_size:
- 4
- 64
- 64
vae: true
wd: 0.0
