# Parámetros de entrenamiento
hiper-parameters:
  # Epocas
  - name: epochs
    type: fixed
    value: 2
    value_type: int

  # Learning rate
  - name: lr
    type: range
    bounds:
      - 1.0E-6
      - 1.0E-3
    log_scale: True
    value_type: float

  # Weight decay
  - name: wd
    type: range
    bounds: 
      - 1.0E-6
      - 1.0E-3
    log_scale: True
    value_type: float

  # Parámetros del modelo

  # Espacio latente
  - name: hidden_size
    type: range
    bounds: 
      - 10
      - 20
    value_type: int
